name: run-tests

description: "Install lance wheel and run unit tests"
inputs:
  python-minor-version:
    required: true
    description: "8 9 10 11 12"
  integration:
    required: false
    description: "Run integration tests"
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Install lancedb
      shell: bash
      run: |
        pip3 install boto3 datasets duckdb ml_dtypes pillow pandas polars[pyarrow,pandas] pytest tensorflow tqdm ruff pre-commit
        pip3 install https://github.com/smartkiwi/lance_backport/releases/download/v0.21.0-beta.5/pylance-0.21.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
        pip3 install --extra-index-url https://pypi.fury.io/lancedb/ $(ls target/wheels/lancedb-*.whl)[tests,dev]
    - name: Setup localstack for integration tests
      if: ${{ inputs.integration == 'true' }}
      shell: bash
      working-directory: .
      run: docker compose up --detach --wait
    - name: pytest (with integration)
      shell: bash
      if: ${{ inputs.integration == 'true' }}
      run: pytest -m "not slow" -x -v --durations=30 python/python/tests
    - name: pytest (no integration tests)
      shell: bash
      if: ${{ inputs.integration != 'true' }}
      run: pytest -m "not slow and not s3_test" -x -v --durations=30 python/python/tests
